<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Квитанция");
?>
<?$APPLICATION->RestartBuffer();?>
<?$APPLICATION->IncludeComponent("bitrix:sale.order.payment","",Array(
    )
);?>
<?die();?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>
